# Generated by Django 4.1.1 on 2022-10-03 11:56

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('book_talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='author',
            name='second_name',
            field=models.CharField(default='Иванович', max_length=30, verbose_name='Отчество'),
        ),
    ]
