# Generated by Django 4.1.1 on 2022-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_talk', '0002_author_birth_date_author_death_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
