# Generated by Django 4.1.1 on 2022-10-10 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_talk', '0004_alter_author_birth_date_alter_author_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_files.file', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
