# Generated by Django 4.1.1 on 2022-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='', verbose_name='Расположение')),
                ('remark', models.CharField(blank=True, max_length=150, verbose_name='Примечание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
        ),
    ]
